### ISSUE TITLE
在danmuku.js的_addToTrack方法中，是否要判定y集合是否为连续数值

### ISSUE THREAD

**Issue by Ye1105** [heeroluo/danmaku-demo#17]
if (y.length >= data.useTracks) {
                data.y = y;
                // y:表示所占轨道序号（下标）的集合有没有可能，y不是顺序的
               // 假设：useTracks=4 ,y=[1,4,5,6],那此时已 data.y[0]作为top，往下4个轨道单位，是会和2,3轨道的前一个最后的弹幕
              // 重叠的？是这样吗

                y.forEach((i) => {
                  this._tracks[i].push(data)
                });
                break;
}

**Comment by Ye1105** [comment]
y.lenth是否需要优化为：y中连续数值出现的个数

**Comment by heeroluo** [comment]
只要出现了一条不可用的轨道，y 就会重置为空数组，所以这里计算的就是连续的可用轨道

**Comment by Ye1105** [comment]
> 只要出现了一条不可用的轨道

嗯嗯，理解了。
