### ISSUE TITLE
  当resize 从大变小时，_removeFromTrack滞后性，此时 this.tracks[i] 可能 undefined,即不存在

### ISSUE THREAD

**Issue by Ye1105** [heeroluo/danmaku-demo#18]
_removeFromTrack(y, id) {
        y.forEach((i) => {
            const track = this._tracks[i];
           // if(typeof track==='undefined')  /* resize 导致 tracks 改变  */
           //  return
          //   当resize 从大变小时，由于_removeFromTrack滞后性，此时 this.tracks[i] 可能 undefined,即不存在
            for (let j = 0; j < track.length; j++) {
                //console.log(track[j].uId,id)
                if (track[j].uId === id) {
                    /* array.splice(index,howmany,item1,......,itemX) */
                    track.splice(j, 1)
                    break
                }
            }
        })
    }

**Comment by heeroluo** [comment]
resize 的时候会移除所有的弹幕元素，被移除元素的 transitionend 就不会触发了，也就不会执行 _removeFromTrack。
当然，从严谨性方面来考虑的话，确实加上这个判断会好一些。

**Comment by Ye1105** [comment]
因为我多次测试的时候，在resize变小的时候，有几次打印日志this.tracks[i]会出现undefined的情况。=。=~

**Comment by heeroluo** [comment]
> 因为我多次测试的时候，在resize变小的时候，有几次打印日志this.tracks[i]会出现undefined的情况。=。=~

可以贴一下你的示例代码吗

**Comment by Ye1105** [comment]
我刚才试了，又都是正常的！！！代码就基本还是你的代码，不得不夸大佬设计得很巧妙！我就改了自定义参数和引用就直接使用的！应该没啥问题，如果以后再遇到问题，我再及时记录

**Comment by Ye1105** [comment]
_renderToDOM 方法中的
        //if (!node) {
        //}
为什么要加这个if 判定我没看懂，我注注释掉在我代码里面正常跑，加了反而不行，我怀疑我又理解错了什么

**Comment by heeroluo** [comment]
node 为 undefined 的时候，表示弹幕的节点还不存在，要创建。
